import {
  AlertCircle,
  ArrowRight,
  BarChart,
  Building,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  Copy,
  Database,
  Download,
  Eye,
  FileText,
  Flag,
  Loader2,
  MessageSquare,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Upload,
  User,
  UserCircle,
  X,
  LayoutDashboard
} from "lucide-react";

export const Icons = {
  logo: Building,
  close: X,
  check: Check,
  user: User,
  alert: AlertCircle,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  fileText: FileText,
  messageSquare: MessageSquare,
  loader: Loader2,
  userCircle: UserCircle,
  barChart: BarChart,
  database: Database,
  building: Building,
  save: Save,
  copy: Copy,
  upload: Upload,
  download: Download,
  refresh: RefreshCw,
  send: Send,
  search: Search,
  eye: Eye,
  clock: Clock,
  settings: Settings,
  flag: Flag,
  layoutDashboard: LayoutDashboard
};